/**
 * Browser wallet service — connects to MetaMask, Phantom, or any
 * EIP-1193 injected provider (window.ethereum).
 *
 * Replaces the old self-custodial WDK seed-phrase flow entirely.
 * Users connect their own testnet/mainnet wallet — no seed phrases
 * generated by the app, no localStorage keys.
 *
 * API surface is intentionally kept identical to the old WDKWalletService
 * so AuthContext, WalletBadge, and StakePrompt need minimal changes.
 */

// ── Standard USDt contract addresses ─────────────────────────────────────────

const USDT_CONTRACTS: Record<string, string> = {
  "1":        "0xdAC17F958D2ee523a2206206994597C13D831ec7", // Ethereum Mainnet
  "11155111": "0x7169D38820dfd117C3FA1f22a697dBA58d90BA06", // Sepolia testnet
  "137":      "0xc2132D05D31c914a87C6611C10748AEb04B58e8F", // Polygon
  "42161":    "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9", // Arbitrum One
};

const ERC20_ABI = [
  "function balanceOf(address owner) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function decimals() view returns (uint8)",
];

// ── EIP-1193 type shim ────────────────────────────────────────────────────────

interface EIP1193Provider {
  request(args: { method: string; params?: unknown[] }): Promise<unknown>;
  on(event: string, handler: (...args: unknown[]) => void): void;
  removeListener(event: string, handler: (...args: unknown[]) => void): void;
}

function getProvider(): EIP1193Provider {
  if (typeof window === "undefined") {
    throw new Error("Wallet is only available in the browser.");
  }
  const win = window as typeof window & { ethereum?: EIP1193Provider };
  if (!win.ethereum) {
    throw new Error(
      "No wallet detected. Install MetaMask or another browser wallet and refresh the page.",
    );
  }
  return win.ethereum;
}

// ── WalletService ─────────────────────────────────────────────────────────────

export class WDKWalletService {
  private _address: string | null = null;

  /** True if the user previously connected (address cached in memory). */
  hasStoredWallet(): boolean {
    // We can't reliably detect a prior connection without asking the provider,
    // so we return false here — the connect() call handles reconnect silently.
    return false;
  }

  /**
   * Request wallet access via MetaMask / Phantom / injected provider.
   * Opens the wallet popup. Returns the first connected account address.
   */
  async connect(): Promise<{ address: string }> {
    const provider = getProvider();
    const accounts = (await provider.request({
      method: "eth_requestAccounts",
    })) as string[];

    if (!accounts || accounts.length === 0) {
      throw new Error("No accounts returned. Please unlock your wallet and try again.");
    }

    this._address = accounts[0].toLowerCase();
    return { address: this._address };
  }

  /** For API compat — same as connect() for injected wallets. */
  async createWallet(): Promise<{ address: string; seedPhrase: string }> {
    const result = await this.connect();
    return { address: result.address, seedPhrase: "" };
  }

  getAddress(): string {
    if (!this._address) throw new Error("Wallet not connected. Call connect() first.");
    return this._address;
  }

  /**
   * Sign a message with personal_sign (eth_sign equivalent).
   * Opens the wallet signature popup.
   */
  async signMessage(message: string): Promise<string> {
    const provider = getProvider();
    const address  = this.getAddress();

    const signature = (await provider.request({
      method: "personal_sign",
      params: [message, address],
    })) as string;

    return signature;
  }

  /** Get native ETH balance. */
  async getBalance(): Promise<bigint> {
    const provider = getProvider();
    const address  = this.getAddress();

    const hex = (await provider.request({
      method: "eth_getBalance",
      params: [address, "latest"],
    })) as string;

    return BigInt(hex);
  }

  /** Get USDt ERC-20 balance on the current network. */
  async getUSDtBalance(): Promise<bigint> {
    const { BrowserProvider, Contract } = await import("ethers");
    const win      = window as typeof window & { ethereum?: EIP1193Provider };
    const provider = new BrowserProvider(win.ethereum as any);
    const network  = await provider.getNetwork();
    const chainId  = network.chainId.toString();
    const usdtAddr = USDT_CONTRACTS[chainId];

    if (!usdtAddr) throw new Error(`USDt not configured for chain ${chainId}`);

    const contract = new Contract(usdtAddr, ERC20_ABI, provider);
    const balance  = await contract.balanceOf(this.getAddress());
    return BigInt(balance.toString());
  }

  /** Transfer USDt ERC-20 tokens. Opens wallet transaction popup. */
  async transferUSDt(to: string, amount: bigint): Promise<string> {
    const { BrowserProvider, Contract } = await import("ethers");
    const win      = window as typeof window & { ethereum?: EIP1193Provider };
    const provider = new BrowserProvider(win.ethereum as any);
    const signer   = await provider.getSigner();
    const network  = await provider.getNetwork();
    const chainId  = network.chainId.toString();
    const usdtAddr = USDT_CONTRACTS[chainId];

    if (!usdtAddr) throw new Error(`USDt not configured for chain ${chainId}`);

    const contract = new Contract(usdtAddr, ERC20_ABI, signer);
    const tx       = await contract.transfer(to, amount);
    const receipt  = await tx.wait();
    return receipt.hash as string;
  }

  /** Sign a stake commitment message. */
  async signStakeCommitment(
    predictionId: string,
    amount: string,
    asset: string,
  ): Promise<string> {
    const message = [
      "ShadowSage — Stake Commitment",
      "",
      `I commit to staking ${amount} ${asset} on prediction ${predictionId}.`,
      "This is a binding commitment to back my football prediction.",
      "",
      `Wallet: ${this.getAddress()}`,
      `Timestamp: ${new Date().toISOString()}`,
    ].join("\n");

    return this.signMessage(message);
  }

  /** Clear in-memory address (does not disconnect the wallet extension). */
  disconnect(): void {
    this._address = null;
  }

  /** No-op for API compat — injected wallets manage their own storage. */
  deleteWallet(): void {
    this.disconnect();
  }

  /** Not applicable for injected wallets. */
  exportSeedPhrase(): string {
    throw new Error("Seed phrase export is not supported for browser wallets.");
  }
}

// Singleton
export const wdkWallet = new WDKWalletService();
